DROP DATABASE Project_2 IF EXISTS;

CREATE DATABASE Project_2;
USE Project_2;

DROP TABLE Movies IF EXISTS;
DROP TABLE Directors IF EXISTS;
DROP TABLE Actors IF EXISTS;
DROP TABLE Movies_Directors IF EXISTS;
DROP TABLE Movies_Actors IF EXISTS;
DROP TABLE Ratings IF EXISTS;
